project_id = "zdfromcouymqcdptjqeb"

[functions.meta-oauth-initiate]
verify_jwt = false

[functions.meta-oauth-callback]
verify_jwt = false

[functions.google-oauth-initiate]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false
